const COPY = {
  en: {
    'nav.home': 'Home',
    'nav.program': 'Program',
    'nav.exercises': 'Exercises',
    'nav.progress': 'Progress',
    'common.today': 'Today',
    'common.minutes': '{count} min',
    'common.kg': '{count}kg',
    'common.closeModal': 'Close modal',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    'common.week': 'week',
    'common.plan': 'plan',
    'home.coachChangedTitle': 'Coach changed this because...',
    'home.startWorkout': 'Start workout',
    'home.openProfileSettings': 'Open profile settings',
    'home.ready': 'Ready to train?',
    'home.streak': 'Streak',
    'home.workouts': 'Workouts',
    'home.time': 'Time',
    'home.targetLine': 'Target: {weight}kg. The coach is using your level, history and weekly rhythm to set today\'s load.',
    'home.todayStimulus': 'Today\'s stimulus',
    'home.coachAdjustment': 'Coach adjustment',
    'home.thisWeek': 'This week',
    'home.sessionsCount': '{count}/{target} sessions',
    'home.weekCopy': 'Stay consistent without chasing punishment.',
    'home.currentChallenge': 'Current challenge',
    'home.challengeCopy': 'Complete {target} clean sessions this week.',
    'home.todaysBlocks': 'Today\'s blocks',
    'home.enableReminders': 'Enable reminders',
    'home.nudge.push': 'You have momentum. Keep it clean and let the last reps stay honest.',
    'home.nudge.deload': 'Today is about leaving fresher than you arrived. Recovery keeps the plan moving.',
    'home.nudge.recovery': 'Restart with control. One completed session brings the rhythm back online.',
    'home.nudge.resume': 'Your unfinished session is waiting. Pick it back up without restarting.',
    'home.nudge.normal': 'Do the next right session. The coach will adapt after your feedback.',
    'onboarding.brand': 'OneBell Coach',
    'onboarding.hero': 'One kettlebell. Adaptive strength.',
    'onboarding.heroBody': 'Tell the coach what you want. It will scale the work to your level.',
    'onboarding.trainingLevel': 'Training level',
    'onboarding.loadQuestion': 'How should the coach load you?',
    'onboarding.equipment': 'Equipment',
    'onboarding.kettlebellWeight': 'Current kettlebell weight',
    'onboarding.weeklyRhythm': 'Weekly rhythm',
    'onboarding.realisticPlan': 'Make the plan realistic',
    'onboarding.daysPerWeek': 'Days per week',
    'onboarding.sessionLength': 'Session length',
    'onboarding.days': '{count} days',
    'onboarding.readinessBaseline': 'Readiness baseline',
    'onboarding.arrivingQuestion': 'How are you arriving?',
    'onboarding.protocolPreview': 'Protocol preview',
    'onboarding.startTraining': 'Start training',
    'goal.burn-fat': 'Burn fat',
    'goal.build-strength': 'Build strength',
    'goal.conditioning': 'Conditioning',
    'goal.burn-fat.detail': 'Short metabolic sessions',
    'goal.build-strength.detail': 'Progressive iron practice',
    'goal.conditioning.detail': 'Capacity, grit, recovery',
    'level.beginner': 'Beginner',
    'level.intermediate': 'Intermediate',
    'level.advanced': 'Advanced',
    'level.beginner.detail': 'More coaching, cleaner reps',
    'level.intermediate.detail': 'Balanced volume and load',
    'level.advanced.detail': 'Higher density, less hand-holding',
    'readiness.low': 'Low energy',
    'readiness.normal': 'Ready',
    'readiness.high': 'Hungry',
    'readiness.low.detail': 'Start conservative',
    'readiness.normal.detail': 'Balanced plan',
    'readiness.high.detail': 'Coach can push',
    'program.method': 'Dynamic method',
    'program.title': 'Your 12-week protocol',
    'program.weekLine': 'Week {week}. The coach adapts the daily work without losing the long arc.',
    'program.workoutsCount': '{completed}/{total} workouts',
    'program.rhythmLine': '{target} sessions per week. Adjust the rhythm later without resetting progress.',
    'program.startToday': 'Start today\'s session',
    'program.phases': 'Program phases',
    'program.phase.weeks': 'Weeks {start}-{end}',
    'program.phase.foundation': 'Foundation',
    'program.phase.foundation.detail': 'Technique, bracing, repeatable reps.',
    'program.phase.build': 'Build',
    'program.phase.build.detail': 'More density, cleaner transitions, stronger sets.',
    'program.phase.performance': 'Performance',
    'program.phase.performance.detail': 'Higher confidence under fatigue.',
    'exercises.library': 'Exercise library',
    'exercises.title': 'Every move has a job',
    'exercises.body': 'Browse by pattern, see what appears today, and open the form card before loading up.',
    'exercises.instructions': 'Instructions',
    'exercises.commonMistakes': 'Common mistakes',
    'exercises.priorityCue': 'Priority cue',
    'filter.all': 'All',
    'filter.today': 'Today',
    'filter.hinge': 'Hinge',
    'filter.squat': 'Squat',
    'filter.press': 'Press',
    'filter.power': 'Power',
    'filter.core': 'Core',
    'filter.carry': 'Carry',
    'profile.language': 'Language',
    'profile.coachSettings': 'Coach settings',
    'profile.tuneCoach': 'Tune the coach',
    'profile.body': 'Change the inputs without losing your workout history.',
    'profile.trainingTarget': 'Training target',
    'profile.goal': 'Goal',
    'profile.level': 'Level',
    'profile.theme': 'Theme',
    'profile.themeDark': 'Dark',
    'profile.themeLight': 'Light',
    'profile.themeSystem': 'System',
    'profile.english': 'English',
    'profile.spanish': 'Español',
    'profile.bodyMetrics': 'Body metrics',
    'profile.bodyMetricsBody': 'Keep height and current weight here. Progress can turn them into trends without changing your training history.',
    'profile.unitSystem': 'Units',
    'profile.metric': 'Metric',
    'profile.imperial': 'Imperial',
    'profile.height': 'Height',
    'profile.bodyWeight': 'Current weight',
    'profile.bmiReference': 'BMI reference',
    'profile.bmiNote': 'BMI is a rough reference, not a full health score.',
    'profile.equipmentRhythm': 'Equipment and rhythm',
    'profile.kettlebell': 'Kettlebell',
    'profile.daysPerWeek': 'Days per week',
    'profile.sessionLength': 'Session length',
    'profile.retention': 'Retention',
    'profile.reminderPermission': 'Reminder permission: {permission}',
    'profile.enableSmartReminders': 'Enable smart reminders',
    'profile.programControl': 'Program control',
    'profile.restartBody': 'Resetting the program start date keeps history, but restarts the 12-week arc from today.',
    'profile.restartArc': 'Restart 12-week arc',
    'profile.backToCoach': 'Back to coach',
    'progress.currentStreak': 'Current streak',
    'progress.progressProof': 'Progress proof',
    'progress.yourWorkVisible': 'Your work is visible',
    'progress.longest': 'Longest: {value}',
    'progress.kcal': 'Kcal',
    'progress.protocolTitle': '12-week protocol',
    'progress.week': 'Week {week}',
    'progress.plannedSessions': '{count}/{total} planned sessions completed. {milestone}.',
    'progress.monthlyActivity': 'Monthly activity',
    'progress.achievements': 'Achievements',
    'progress.days.mon': 'M',
    'progress.days.tue': 'T',
    'progress.days.wed': 'W',
    'progress.days.thu': 'T',
    'progress.days.fri': 'F',
    'progress.days.sat': 'S',
    'progress.days.sun': 'S',
    'workout.completeSet': 'Complete set',
    'workout.formGuide': 'Form guide',
    'workout.coachCue': 'Coach cue',
    'workout.startNextSet': 'Start next set',
    'workout.complete': 'Workout complete',
    'workout.workDone': 'Work done',
    'workout.duration': 'Duration',
    'workout.focus': 'Focus',
    'workout.easy': 'Easy',
    'workout.correct': 'Correct',
    'workout.brutal': 'Brutal',
    'workout.pain': 'Pain',
    'workout.optionalNote': 'Optional note for the coach',
    'workout.saveSession': 'Save session',
    'workout.warmup': 'Warmup {current}/{total}',
    'workout.warmupFallback': 'Warmup',
    'workout.warmupInstructionFallback': 'Move with control and prepare the joints you are about to load.',
    'workout.recoveryPhase': 'Recovery phase',
    'workout.lockedIn': '{name} locked in',
    'workout.seconds': 'sec',
    'workout.upNext': 'Up next',
    'workout.restCue': 'Breathe through your nose, shake out tension, keep the next set crisp.',
    'workout.exerciseCount': 'Exercise {current}/{total}',
    'workout.target': 'Target',
    'workout.rest': 'Rest',
    'workout.closeSession': 'Close session',
    'workout.fallbackInstruction1': 'Keep your core braced.',
    'workout.fallbackInstruction2': 'Move with control.',
    'workout.fallbackInstruction3': 'Stop if pain appears.',
    'workout.fallbackMistake1': 'Rushing reps.',
    'workout.fallbackMistake2': 'Losing posture.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.program': 'Programa',
    'nav.exercises': 'Ejercicios',
    'nav.progress': 'Progreso',
    'common.today': 'Hoy',
    'common.minutes': '{count} min',
    'common.kg': '{count}kg',
    'common.closeModal': 'Cerrar modal',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.continue': 'Continuar',
    'common.week': 'semana',
    'common.plan': 'plan',
    'home.coachChangedTitle': 'El coach cambió esto porque...',
    'home.startWorkout': 'Empezar entrenamiento',
    'home.openProfileSettings': 'Abrir ajustes de perfil',
    'home.ready': '¿Listo para entrenar?',
    'home.streak': 'Racha',
    'home.workouts': 'Sesiones',
    'home.time': 'Tiempo',
    'home.targetLine': 'Carga: {weight}kg. El coach usa tu nivel, historial y ritmo semanal para ajustar la sesión de hoy.',
    'home.todayStimulus': 'Estímulo de hoy',
    'home.coachAdjustment': 'Ajuste del coach',
    'home.thisWeek': 'Esta semana',
    'home.sessionsCount': '{count}/{target} sesiones',
    'home.weekCopy': 'Sé constante sin convertirlo en castigo.',
    'home.currentChallenge': 'Reto actual',
    'home.challengeCopy': 'Completa {target} sesiones limpias esta semana.',
    'home.todaysBlocks': 'Bloques de hoy',
    'home.enableReminders': 'Activar recordatorios',
    'home.nudge.push': 'Traes impulso. Mantén reps limpias y honestas hasta el final.',
    'home.nudge.deload': 'Hoy se trata de terminar más fresco. Recuperar también mueve el plan.',
    'home.nudge.recovery': 'Vuelve con control. Una sesión completada recupera el ritmo.',
    'home.nudge.resume': 'Tu sesión pendiente te espera. Retómala sin empezar desde cero.',
    'home.nudge.normal': 'Haz la siguiente sesión correcta. El coach ajustará después de tu feedback.',
    'onboarding.brand': 'OneBell Coach',
    'onboarding.hero': 'Una kettlebell. Fuerza adaptativa.',
    'onboarding.heroBody': 'Dile al coach qué buscas. Ajustará el trabajo a tu nivel.',
    'onboarding.trainingLevel': 'Nivel de entrenamiento',
    'onboarding.loadQuestion': '¿Cómo debe cargarte el coach?',
    'onboarding.equipment': 'Equipo',
    'onboarding.kettlebellWeight': 'Peso actual de kettlebell',
    'onboarding.weeklyRhythm': 'Ritmo semanal',
    'onboarding.realisticPlan': 'Haz que el plan sea realista',
    'onboarding.daysPerWeek': 'Días por semana',
    'onboarding.sessionLength': 'Duración de sesión',
    'onboarding.days': '{count} días',
    'onboarding.readinessBaseline': 'Energía base',
    'onboarding.arrivingQuestion': '¿Cómo llegas hoy?',
    'onboarding.protocolPreview': 'Vista previa del protocolo',
    'onboarding.startTraining': 'Empezar a entrenar',
    'goal.burn-fat': 'Quemar grasa',
    'goal.build-strength': 'Ganar fuerza',
    'goal.conditioning': 'Acondicionamiento',
    'goal.burn-fat.detail': 'Sesiones metabólicas cortas',
    'goal.build-strength.detail': 'Práctica progresiva con kettlebell',
    'goal.conditioning.detail': 'Capacidad, energía y recuperación',
    'level.beginner': 'Principiante',
    'level.intermediate': 'Intermedio',
    'level.advanced': 'Avanzado',
    'level.beginner.detail': 'Más guía, reps más limpias',
    'level.intermediate.detail': 'Volumen y carga balanceados',
    'level.advanced.detail': 'Más densidad, menos asistencia',
    'readiness.low': 'Poca energía',
    'readiness.normal': 'Listo',
    'readiness.high': 'Con ganas',
    'readiness.low.detail': 'Empezar conservador',
    'readiness.normal.detail': 'Plan balanceado',
    'readiness.high.detail': 'El coach puede empujar',
    'program.method': 'Método dinámico',
    'program.title': 'Tu protocolo de 12 semanas',
    'program.weekLine': 'Semana {week}. El coach adapta el trabajo diario sin perder el arco completo.',
    'program.workoutsCount': '{completed}/{total} sesiones',
    'program.rhythmLine': '{target} sesiones por semana. Ajusta el ritmo después sin reiniciar tu progreso.',
    'program.startToday': 'Empezar sesión de hoy',
    'program.phases': 'Fases del programa',
    'program.phase.weeks': 'Semanas {start}-{end}',
    'program.phase.foundation': 'Base',
    'program.phase.foundation.detail': 'Técnica, braceo y reps repetibles.',
    'program.phase.build': 'Construcción',
    'program.phase.build.detail': 'Más densidad, transiciones limpias y series más fuertes.',
    'program.phase.performance': 'Rendimiento',
    'program.phase.performance.detail': 'Más confianza bajo fatiga.',
    'exercises.library': 'Biblioteca de ejercicios',
    'exercises.title': 'Cada movimiento tiene un propósito',
    'exercises.body': 'Filtra por patrón, ve qué aparece hoy y abre la guía técnica antes de cargar.',
    'exercises.instructions': 'Instrucciones',
    'exercises.commonMistakes': 'Errores comunes',
    'exercises.priorityCue': 'Cue prioritario',
    'filter.all': 'Todos',
    'filter.today': 'Hoy',
    'filter.hinge': 'Bisagra',
    'filter.squat': 'Sentadilla',
    'filter.press': 'Empuje',
    'filter.power': 'Potencia',
    'filter.core': 'Core',
    'filter.carry': 'Carga',
    'profile.language': 'Idioma',
    'profile.coachSettings': 'Ajustes del coach',
    'profile.tuneCoach': 'Ajusta el coach',
    'profile.body': 'Cambia los datos sin perder tu historial de entrenamiento.',
    'profile.trainingTarget': 'Objetivo de entrenamiento',
    'profile.goal': 'Objetivo',
    'profile.level': 'Nivel',
    'profile.theme': 'Tema',
    'profile.themeDark': 'Oscuro',
    'profile.themeLight': 'Claro',
    'profile.themeSystem': 'Sistema',
    'profile.english': 'English',
    'profile.spanish': 'Español',
    'profile.bodyMetrics': 'Métricas corporales',
    'profile.bodyMetricsBody': 'Guarda aquí altura y peso actual. Progreso podrá convertirlos en tendencias sin cambiar tu historial de entrenamiento.',
    'profile.unitSystem': 'Unidades',
    'profile.metric': 'Métrico',
    'profile.imperial': 'Imperial',
    'profile.height': 'Altura',
    'profile.bodyWeight': 'Peso actual',
    'profile.bmiReference': 'Referencia IMC',
    'profile.bmiNote': 'El IMC es una referencia general, no una calificación completa de salud.',
    'profile.equipmentRhythm': 'Equipo y ritmo',
    'profile.kettlebell': 'Kettlebell',
    'profile.daysPerWeek': 'Días por semana',
    'profile.sessionLength': 'Duración de sesión',
    'profile.retention': 'Retención',
    'profile.reminderPermission': 'Permiso de recordatorios: {permission}',
    'profile.enableSmartReminders': 'Activar recordatorios inteligentes',
    'profile.programControl': 'Control del programa',
    'profile.restartBody': 'Reiniciar la fecha del programa conserva tu historial, pero vuelve a empezar el arco de 12 semanas desde hoy.',
    'profile.restartArc': 'Reiniciar arco de 12 semanas',
    'profile.backToCoach': 'Volver al coach',
    'progress.currentStreak': 'Racha actual',
    'progress.progressProof': 'Prueba de progreso',
    'progress.yourWorkVisible': 'Tu trabajo ya se ve',
    'progress.longest': 'Mejor: {value}',
    'progress.kcal': 'Kcal',
    'progress.protocolTitle': 'Protocolo de 12 semanas',
    'progress.week': 'Semana {week}',
    'progress.plannedSessions': '{count}/{total} sesiones planeadas completadas. {milestone}.',
    'progress.monthlyActivity': 'Actividad mensual',
    'progress.achievements': 'Logros',
    'progress.days.mon': 'L',
    'progress.days.tue': 'M',
    'progress.days.wed': 'M',
    'progress.days.thu': 'J',
    'progress.days.fri': 'V',
    'progress.days.sat': 'S',
    'progress.days.sun': 'D',
    'workout.completeSet': 'Terminar set',
    'workout.formGuide': 'Guía de técnica',
    'workout.coachCue': 'Cue del coach',
    'workout.startNextSet': 'Empezar siguiente set',
    'workout.complete': 'Entrenamiento completo',
    'workout.workDone': 'Trabajo hecho',
    'workout.duration': 'Duración',
    'workout.focus': 'Foco',
    'workout.easy': 'Fácil',
    'workout.correct': 'Correcto',
    'workout.brutal': 'Brutal',
    'workout.pain': 'Dolor',
    'workout.optionalNote': 'Nota opcional para el coach',
    'workout.saveSession': 'Guardar sesión',
    'workout.warmup': 'Calentamiento {current}/{total}',
    'workout.warmupFallback': 'Calentamiento',
    'workout.warmupInstructionFallback': 'Muévete con control y prepara las articulaciones que vas a cargar.',
    'workout.recoveryPhase': 'Fase de recuperación',
    'workout.lockedIn': '{name} registrado',
    'workout.seconds': 'seg',
    'workout.upNext': 'Sigue',
    'workout.restCue': 'Respira por la nariz, suelta tensión y mantén limpio el siguiente set.',
    'workout.exerciseCount': 'Ejercicio {current}/{total}',
    'workout.target': 'Objetivo',
    'workout.rest': 'Descanso',
    'workout.closeSession': 'Cerrar sesión',
    'workout.fallbackInstruction1': 'Mantén el core activo.',
    'workout.fallbackInstruction2': 'Muévete con control.',
    'workout.fallbackInstruction3': 'Detente si aparece dolor.',
    'workout.fallbackMistake1': 'Apurar las reps.',
    'workout.fallbackMistake2': 'Perder postura.',
  },
};

export function getLanguage(profile = {}) {
  return profile.language === 'es' ? 'es' : 'en';
}

export function t(key, language = 'en', params = {}) {
  const normalized = language === 'es' ? 'es' : 'en';
  const value = COPY[normalized][key] || COPY.en[key] || key;
  return interpolate(value, params);
}

export function formatDate(value, language = 'en', options = { weekday: 'long', month: 'short', day: 'numeric' }) {
  return new Intl.DateTimeFormat(language === 'es' ? 'es-MX' : 'en', options).format(new Date(value));
}

export function formatDayCount(count = 0, language = 'en') {
  const days = Number(count) || 0;
  if (language === 'es') return `${days} ${days === 1 ? 'día' : 'días'}`;
  return `${days} ${days === 1 ? 'day' : 'days'}`;
}

export function formatSessionCount(count = 0, language = 'en') {
  const sessions = Number(count) || 0;
  if (language === 'es') return `${sessions} ${sessions === 1 ? 'sesión' : 'sesiones'}`;
  return `${sessions} ${sessions === 1 ? 'session' : 'sessions'}`;
}

function interpolate(value, params) {
  return Object.entries(params).reduce(
    (text, [key, paramValue]) => text.replaceAll(`{${key}}`, String(paramValue)),
    value,
  );
}
